### ISSUE TITLE
npm server - error when try to start server

### ISSUE THREAD

**Issue by SallyZ12** [learn-co-curriculum/react-updating-state-lab#12]
when use "npm server" server does not start, error messages result.  When follow instructions to resolve, does not resolve.  Therefore, just used "tests" with no browser feed-back for this lab.

**Comment by blainelawson** [comment]
Same.

**Comment by maxwellbenton** [comment]
Hi @SallyZ12,

Thank you for opening this issue. We've tested this lab and have confirmed that `npm start` will display the app correctly, but because of the way this lab is designed, it isn't possible to see progress until both components are defined and exported. We've added some additional information in the Readme including instructions for commenting out the second component while working on the first in order to view it in the browser.

I'm not 100% sure this is the issue that you were having, but I am able to confirm that the lab is working currently and has been improved based on your feedback. Thank you for contributing!
